INSERT INTO MYTABLE (NAME, PRICE)
 VALUES ('bred', 12);
INSERT INTO MYTABLE (NAME, PRICE)
 VALUES ('milk', 123);
INSERT INTO MYTABLE (NAME, PRICE)
 VALUES ('meet', 1230);
INSERT INTO PUBLIC.PUBLIC.MYTABLE (NAME, PRICE)
 VALUES ('cheese', 56567);
INSERT INTO PUBLIC.PUBLIC.MYTABLE (NAME, PRICE)
 VALUES ('apple', 123567);
INSERT INTO PUBLIC.PUBLIC.MYTABLE (NAME, PRICE)
 VALUES ('bananas', 12563);
INSERT INTO PUBLIC.PUBLIC.MYTABLE (NAME, PRICE)
 VALUES ('lemon', 123567);
INSERT INTO PUBLIC.PUBLIC.MYTABLE (NAME, PRICE)
 VALUES ('coffee', 123567);