INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX2', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX3', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX4', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX5', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX6', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX7', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX8', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX9', '123', false);
INSERT INTO PUBLIC.PUBLIC.USERS (LOGIN, PASSWORD,STATUS)
 VALUES ('ALEX10', '123', false);